url: "https://cufas.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "CUFAS" # the name of your site, e.g. ACME Corp.
tagline: Cambridge Universities First Aid Society
description: CUPor is a society at the University of Cambridge that brings together members of the University that are Portuguese or are interested in Portuguese culture.
logo: assets/images/logo-circle.png
sass:
  style: compressed
nav_dropdowns:
  - about.md
  - constitution.md
  - committee.html

