name: Update website
on: [push]
jobs:
  build:
    name: Execute on sinkhole
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: webserver.srcf.net
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/firstaid/cufas-web
          export PATH=$PATH:$HOME/bin
          make BUILDDIR=../public_html
